### ISSUE TITLE
Add Crashlytics JS client

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Kermit#119]
Not sure there is a JS client, but if there is, add JS support

**Comment by faogustavo** [comment]
Crashlytics is only available for Android, iOS and Unity.

![Screenshot_2021-08-30-21-06-21-116_com.android.chrome.jpg](https://user-images.githubusercontent.com/7588480/131421291-7c8c480a-b0f3-441f-82d3-bcb31f46e704.jpg)

**Comment by kpgalligan** [comment]
👍
