### ISSUE TITLE
Test updates

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Kermit#139]
We should move the tests in `KermitTest` tests to `LoggerTest` to reflect the rename.

For global, we should add tests for the global config methods. These include `setMinSeverity`, `setLogWriters` (list and vararg versions), `addLogWriter` and `setDefaultTag`.

I'd also like some tests to explicitly create an instance of `MutableLoggerConfig` and use that. Just confirm that changing the values does in fact change what they do. I'd say just add the test log writer, then confirm that changing the min severity and default tag works.

For now I think that's kind of it unless we can think of other things to test.

**Comment by findjigar** [comment]
Work done in #144 which got incorrectly got squashed and merged via #143 

Closing the issue now!
