### ISSUE TITLE
Unresolved reference to Logger

### ISSUE THREAD

**Issue by francismariano** [touchlab/Kermit#147]
Hello folks,

I am trying to use the version 0.3.0-m1 of Kermit, but the AS do not resolve all the methods.

Gradle version: 7.2
Kotlin version: 1.5.31

![image](https://user-images.githubusercontent.com/21108555/134373207-d0f88cd2-c132-4e2b-939d-2e8a351ded07.png)

I followed the steps described on the Basic Config.

**Comment by mrf7** [comment]
Hi, Kermit is currently undergoing a major refactor and api change so the docs are actually ahead of the most recent public release (`0.3.1-m1`). We're planning on making a beta release later today with all the api changes and new features shown in the current docs like static logging. Will update this issue when that release goes out!

**Comment by mrf7** [comment]
@francismariano beta release with this api is live! Try updating your version to `1.0.0-rc1`

**Comment by francismariano** [comment]
Thank you so much
