### ISSUE TITLE
SystemWriter adding unnecessary characters 

### ISSUE THREAD

**Issue by chrimaeon** [touchlab/Kermit#180]
Is it on purpose that the  JVM's`SystemWriter` add `")` at the end of the message?

https://github.com/touchlab/Kermit/blob/da10a75f15e5dd43672f8fe4d3d2cf6dd96c210e/kermit/src/jvmMain/kotlin/co/touchlab/kermit/SystemWriter.kt#L6

**Comment by kpgalligan** [comment]
No, that's wrong. Fixing. Thanks!
