### ISSUE TITLE
Setup crashlitics

### ISSUE THREAD

**Issue by IlyasNN** [touchlab/Kermit#214]
Can't integrate kermit-crashlitics and setup it.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50013971/146528884-3bdbc2f4-7014-48a9-9b4f-c00c66150b7a.png">
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/50013971/146528898-5fdfdccc-10fc-4e2e-ac0f-27457bd96659.png">

Have no ideas why. Maybe because of MacBook Air m1...

**Comment by kpgalligan** [comment]
We publish M1 libraries, and I'm not sure that would be an issue anyway. Do you have hierarchical source sets in gradle.properties?

```
kotlin.mpp.enableGranularSourceSetsMetadata=true
kotlin.native.enableDependencyPropagation=false
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.commonizerLogLevel=info
```
