### ISSUE TITLE
Draft plan for Koin "getWithTag" helper

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Kermit#230]
we want a helper for Koin that makes getting with tags easier. See https://github.com/touchlab/KaMPKit/blob/main/shared/src/commonMain/kotlin/co/touchlab/kampkit/Koin.kt#L68 for a more generic example.

We're going to have a Koin-specific module in Kermit, so adding this is another thing that's useful and I've added a few times manually. This compiles and does what we want, so let's try this:

```kotlin
inline fun <reified Logger> Scope.getLoggerWithTag(tag: String): Logger {
    return get(parameters = { parametersOf(tag) })
}
```

**Comment by russhwolf** [comment]
inline fun <reified L: Logger> Scope.getLoggerWithTag(tag: String): L

**Comment by russhwolf** [comment]
Or maybe it doesn't need a generic and it's just `inline fun Scope.getLoggerWithTag(tag: String): Logger`

**Comment by russhwolf** [comment]
We should probably do the other side of this too, ie the koin `faktory { }` statement that binds the logger with a tag parameter.

**Comment by TadeasKriz** [comment]
> Or maybe it doesn't need a generic and it's just `inline fun Scope.getLoggerWithTag(tag: String): Logger`

Yeah I wasn't sure if there's subclasses of `Logger` that the API consumers might be interested in getting.
