### ISSUE TITLE
[Question] With version 1.1.0 tag appears as suffix instead of prefix (on iOS)

### ISSUE THREAD

**Issue by GuilhE** [touchlab/Kermit#243]
With Kermit 1.0.0: 
```
Logger.withTag("my tag")
logger.d { "some loging" }
```
output: `(my tag) some loging`

With Kermit 1.1.0:
```
Logger.withTag("my tag")
logger.d { "some loging" }
```
output: `(some loging) my tag`

Is it a bug or a configuration?

**Comment by kpgalligan** [comment]
I'll take a look. That's odd.

**Comment by kpgalligan** [comment]
What's your config, btw? What platform(s)?

**Comment by GuilhE** [comment]
> What's your config, btw? What platform(s)?

Android & iOS, the loging operations are called in the shared module.

**Comment by kpgalligan** [comment]
Hmm. Code looks normal but I'll try it out. Working on Kermit a bit today anyway

**Comment by GuilhE** [comment]
I believe it could be a misplaced parameter, looking at:
https://github.com/touchlab/Kermit/blob/8134f5243d2134fea1d63ef3e7f101373bd6807c/kermit/src/darwinMain/kotlin/co/touchlab/kermit/XcodeSeverityWriter.kt#L15

and having Kermit 1.1.0 printing `(some loging) my tag`, it could be some caller's fault. I took a quick look but couldn't find it though. I'm not acquaintance with the code either.

**Comment by kpgalligan** [comment]
Yeah. Totally my fault on a os log refactor. Adding a test. I'm pretty surprised that got past visual review considering how much tweaking went into the log write, but there was no test catching that. Will be out soon. You do a workaround making your own subclass of `OSLogWriter`.

**Comment by kpgalligan** [comment]
https://github.com/touchlab/Kermit/releases/tag/1.1.1
