### ISSUE TITLE
I want to add custom key logs when get crashed

### ISSUE THREAD

**Issue by Shashank02051997** [touchlab/Kermit#248]
Hi,
Firstly thank you for this wonderful Kermit logging library.  I have a question here for the logging library suppose I want to log custom keys into the firebase if there are any crashes happened then is there any method to expose the custom keys there

This is a method exposed by the firebase but I think it is private at your end so any suggestion at your end so how could anyone add custom logs while the app is getting crashed on a firebase 
<img width="866" alt="Screenshot 2022-04-25 at 5 31 33 PM" src="https://user-images.githubusercontent.com/20399094/165085524-01bceddf-3025-436c-ac79-47a0ee7a7733.png">

**Comment by kpgalligan** [comment]
Older issue. Closing. For reference, Kermit uses CrashKiOS for Crashlytics. Kermit just has a log writer that adds logs to Crashlytics. To add custom keys, call CrashKiOS directly: https://crashkios.touchlab.co/docs/crashlytics#sending-extra-info-to-crashlytics
