### ISSUE TITLE
Integration with Kermit and crashlytics

### ISSUE THREAD

**Issue by yosephws** [touchlab/Kermit#254]
I am using kotlin 1.6.10

with this option on ios project 
`linkerOpts.add("-lsqlite3")`

Tried to add Kermit library to the dependancies
```
    const val kermit = "co.touchlab:kermit:$version"
    const val crashlytics = "co.touchlab:kermit-crashlytics:$version"

```
the version is 1.0.0

it can build and create framework fine but when I used and ran it on simulator xCode, it give me this error logs [](url)

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img width="430" alt="Screen Shot 2022-05-12 at 12 44 17" src="https://user-images.githubusercontent.com/66290083/167988295-66cf289b-d89b-4d68-81c6-eb347a8c71e7.png">

IF i removed Kermits completely, its working perfectly fine.

IS there something I missed?

**Comment by samhill303** [comment]
The sqlite issues don't seem to be related to kermit/crashlytics. Please let us know if you still have this issue and have a simple reproducing project to share
