### ISSUE TITLE
Koin publishing issues

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Kermit#255]
https://kotlinlang.slack.com/archives/C3PQML5NU/p1652949467215949

**Comment by xxfast** [comment]
Mirroring the conversation here

Trying to use `kermit-koin`, 
```kotlin
 implementation("co.touchlab:kermit-koin:1.1.2")
```
but im running into this

```
Could not resolve org.jetbrains.kotlin:kotlin-test:1.6.20.
Required by:
    project :login > co.touchlab:kermit-koin:1.1.2 > co.touchlab:kermit-koin-jvm:1.1.2
    project :login > co.touchlab:kermit-koin:1.1.2 > co.touchlab:kermit-koin-jvm:1.1.2 > org.jetbrains.kotlin:kotlin-test-junit:1.6.20
```
Also, i don't get why there's a test dependency here. Is there a reason for this dependency to `kotlin-test-junit`, when we are just using this for `implementation()`
