### ISSUE TITLE
Logging on a desktop JVM

### ISSUE THREAD

**Issue by mipastgt** [touchlab/Kermit#263]
While reading the documentation I can't find any hints on logging on a desktop JVM. Isn't that supported or did I just miss something. Actually I was hoping to find some logging interface to the popular SLF4J facade which is heavily used in the JVM world.

**Comment by psh** [comment]
It's true, Kermit doesnt have built-in support for SLF4J.  That said, it does support users who want to supply their own implementation of the abstract [LogWriter class](https://github.com/touchlab/Kermit/blob/a781a37a39732882162fd3fa1883b49d3d7cd52d/kermit/src/commonMain/kotlin/co/touchlab/kermit/LogWriter.kt) - it boils down to implementing one method - so might be as simple as writing along the lines of

```kotlin
class Slf4jLogWriter : LogWriter() {
    override fun log(severity: Severity, message: String, tag: String, throwable: Throwable?) {
        val builder = LoggerFactory.getLogger(tag)
            .atLevel(severity.slf4jLevel)

        if (throwable != null) {
            builder.setCause(throwable)
        }

        builder.log(message)
    }

    // No perfect match between the respective logging levels, but this might be close enough
    private val Severity.slf4jLevel: Level
        get() = when (this) {
            Severity.Verbose -> Level.TRACE
            Severity.Debug -> Level.DEBUG
            Severity.Info -> Level.INFO
            Severity.Warn -> Level.WARN
            Severity.Error -> Level.ERROR
            Severity.Assert -> Level.ERROR
        }
}
```
