### ISSUE TITLE
Kermit Koin 1.1.3 is incompatible with Kotlin Test 1.7.0

### ISSUE THREAD

**Issue by thipokch** [touchlab/Kermit#264]
Gradle is unable to resolve dependencies when `kotlin-test:1.7.0`  with `kermit-koin:1.1.3`.

```
'co.touchlab:kermit-koin:1.1.3' (debugRuntimeElements-published) --> 'co.touchlab:kermit-koin-android-debug:1.1.3' (debugRuntimeElements-published) --> 'org.jetbrains.kotlin:kotlin-test:1.6.20'

'org.jetbrains.kotlin:kotlin-test:{strictly 1.6.20}' because of the following reason: debugRuntimeClasspath uses version 1.6.20
```

**Comment by kpgalligan** [comment]
Do you have some config you could post?

**Comment by thipokch** [comment]
@kpgalligan Here's the gradle config with sample project 
https://github.com/thipokch/kmm-demo/blob/fde6a79a76cb0cc8612fac60f4dab4bc21cc445f/shared/build.gradle.kts

**Comment by thipokch** [comment]
@kpgalligan should I do a PR?

**Comment by mrf7** [comment]
Hi @thipokch, I was able to recreate the error in your demo project and updating to the newest version of kermit (`1.2.2`) seems to fix it. Does that fix things for you?

**Comment by thipokch** [comment]
@mrf7 It's fixed now. Thanks!
