### ISSUE TITLE
LOG_WRITER.md outdated?

### ISSUE THREAD

**Issue by harry248** [touchlab/Kermit#265]
Is the documentation at https://github.com/touchlab/Kermit/blob/main/docs/LOG_WRITER.md outdated? Setting NSLogWriter doesn't work because the class is not found. Same for the others except CommonWriter.

**Comment by mrf7** [comment]
Hey @harry248, `NSLogWriter` and the others are still available in the most recent version. If you only see `CommonWriter` it sounds like you're in the `commonMain` source set. The platform specific `LogWriter`s like `NSLogWriter` and `LogcatWriter` are only available in the sourceset for that platform (iosMain and androidMain respectively). 

The example `Logger.setLogWriters(...)` snippet at the beginning of that doc is an example of the Android side of initializing Kermit, in which case there would also be a similar call in the iOS sourceset passing `NSLogWriter`. If you want a simpler set up that just uses the platform defaults you can just use the global `Logger` without any setup.

If you're trying to do a more custom set up with different `LogWriter`s you can use the `platformLogWriter()` helper function that's available in common code and will add the default writer for each platform automatically
