### ISSUE TITLE
ios: Crash on logging message strings containing '%n'

### ISSUE THREAD

**Issue by awmwong** [touchlab/Kermit#266]
A crash occurs on iOS devices if one tries to log a message containing the string "%n".

The minimal repro case I could find is simply: `Log.i { "%n" }`

This looks like to be an instance of this here: https://stackoverflow.com/questions/64055927/save-38-now-c-string-aborts-the-program -- `OSLogWriter` is using `_os_log_internal()`

Was there a particular reason to use `_os_log_internal` vs `os_log`?

**Comment by micbakos** [comment]
Same thing here. In my case I have integrated Kermit with Ktor. The same crash occurs with the encoded version of `%n`=>`%25n`
