### ISSUE TITLE
Kermit Crash Logging - AppCenter

### ISSUE THREAD

**Issue by aclassen** [touchlab/Kermit#269]
If someone is interested :
https://github.com/aclassen/kermit-appcenter
Unfortunately AppCenter does not support simple logging and also not adding properties to the crash that will be send by the sdk.
So the logger will send an handled exception alongside the crash with a readable stacktrace.

**Comment by psh** [comment]
FYI - 
> Visual Studio App Center is scheduled for retirement on March 31, 2025. After that date, it will not be possible to sign in with your user account nor make API calls. App Center will continue to be supported until March 31, 2025, with critical bug fixes and technical support.

from https://learn.microsoft.com/en-us/appcenter/retirement

**Comment by kpgalligan** [comment]
Closing due to pending retirement of the service
