### ISSUE TITLE
Kermit - 1.8 Beta Testing

### ISSUE THREAD

**Issue by KatieGalvin** [touchlab/Kermit#312]
Perform the list of sanity checks on your work projects (it mostly consists of basic actions).

- Compile your project with a current Kotlin version.
- Check the highlighting in different IDE modules.
- Compile the project with the EAP Kotlin version and install the EAP IDE plugin.
- Verify that the project re-imported successfully.
- Check that highlighting from p.2 works not worse than before.
- Compile the project again and look for new surprising warnings.
- Change something in the code and check if incremental compilation works.
- Run your tests with a new Kotlin version.
- Stop at some well-known piece of code, run the debugger and try stepping.
- Look for performance issues in compilation, runtime, re-import or IDE behavior.

Pay additional attention to these features and subsystems if applicable to your use case:

- Kotlin Gradle plugin: lots of changes in all typical usage scenarios
- The new Gradle Incremental compilation, which we plan to stabilize soon
- Expose compiler flags via Gradle lazy properties
- Ability to not fallback with compiler daemon by default
- arm64 support for watchOS targets
- Xcode 14 and new Objective-C frameworks support in Kotlin/Native

**Comment by samhill303** [comment]
Test RC version, not beta now that it's out
