### ISSUE TITLE
Docs for crashlytics unhandled exception hook are out of date

### ISSUE THREAD

**Issue by rocketraman** [touchlab/Kermit#315]
The docs for iOS reference setting up the exception hook as follows:

```
setupCrashlyticsExceptionHook(Logger)
```

However, it appears on the latest releases, this is no longer the correct call. It now appears to be:

```
import co.touchlab.kermit.crashlytics.setCrashlyticsUnhandledExceptionHook

setCrashlyticsUnhandledExceptionHook()
```

Should be updated: https://github.com/touchlab/Kermit/blob/main/kermit-crashlytics/README.md?plain=1#L42

**Comment by kpgalligan** [comment]
Kermit no longer manages crash reporting directly. It just calls [CrashKiOS](https://crashkios.touchlab.co/) methods for logging.
