### ISSUE TITLE
Kermit Evaluate Simplified Sample Set

### ISSUE THREAD

**Issue by KatieGalvin** [touchlab/Kermit#316]
Some of the samples may be easier to demonstrate through documentation (and be easier to maintain).

Remove all but one primary sample. For each removed sample, write a doc/tutorial which demonstrates the concept we were demonstrating in the sample. 

The primary sample should be similar to what is currently `sample-production` except we don't want to include kermit-crashlytics.

**Comment by samhill303** [comment]
Needs expansion to include which documents we want to create based on our existing docs and what the samples include
