### ISSUE TITLE
Unable to setup Crashlytics  - Unresolved reference

### ISSUE THREAD

**Issue by schmidt9** [touchlab/Kermit#324]
I followed this manual https://github.com/touchlab/Kermit/blob/main/kermit-crashlytics/README.md#step-2-setup-kermit-crash-logging, but was unable to build my app because of import issue, this is screenshot from `iosMain` target. What's wrong here?

![Снимок экрана 2023-02-03 в 17 03 38](https://user-images.githubusercontent.com/20910077/216623237-86f9a570-689c-4c1c-8293-c1be75df3bec.png)

**Comment by kpgalligan** [comment]
Looks like the docs need to be fixed. We updated a lot of how the crash reporting works under the hood in the last release.

Here's the call: https://github.com/touchlab/Kermit/blob/main/samples/sample-crashlytics/shared/src/iosMain/kotlin/co/touchlab/kermitsample/Helper.kt#L21

```kotlin
setCrashlyticsUnhandledExceptionHook()
```

I updated that doc. Let me know if that works.

**Comment by schmidt9** [comment]
> I updated that doc. Let me know if that works.

You did not update sorry https://github.com/touchlab/Kermit/blob/main/kermit-crashlytics/README.md#ios

**Comment by schmidt9** [comment]
But it works now thanks
