### ISSUE TITLE
Logs not logged on iOS

### ISSUE THREAD

**Issue by ubuntudroid** [touchlab/Kermit#327]
I've setup Kermit in a little multi-platform app, and it works like a charm on Android, both when logging from the Android code and from the shared code. However, on iOS, logs aren't logged—neither from my Swift code nor from the shared code.

Any idea what might be causing this? Do I have to do some additional initialization on iOS and I have missed it in the docs?

**Comment by kpgalligan** [comment]
I think we'd need to see your config. Also, where are you looking for logs, and if you log directly from Swift (not through Kermit) can you confirm they show up as expected?

**Comment by ubuntudroid** [comment]
Oh my, my bad—I found that the logs indeed show, but only if checking the log in Xcode, not in Android Studio. 🤔 Do you know whether there is some kind of filtering going on in the Android Studio iOS log display and how to disable it?

**Comment by sunildhiman90** [comment]
@kpgalligan I also have same issue in compose multiplatform project. Working fine on all platforms except iOS. And in my case its not even working from xocde also.  Whats the exact setup we need to do for iOS?

**Comment by kpgalligan** [comment]
@sunildhiman90 Well, in theory, this isn't the same issue because it was working for the other dev. There's nothing special you should need to do, so we'd need a repro to try out.

**Comment by sunildhiman90** [comment]
Hi, i just created a new branch in my KMP template here:
https://github.com/sunildhiman90/Compose-Multiplatform-App-Template-KMP/tree/with_kermit
you can check this out. ANd let me know if i  am doing something wrong

**Comment by psh** [comment]
@sunildhiman90 I took a look at the repo.  The "with_kermit" and the "main" branch are the same in terms of commits, and neither include any reference to Kermit. Did you miss a commit?

**Comment by kpgalligan** [comment]
Had the same...

**Comment by sunildhiman90** [comment]
Sorry for that. I forgot to add the commit. You can check now @psh and @kpgalligan

**Comment by kpgalligan** [comment]
@sunildhiman90 Pulled you code, ran it. Seems to be fine. If you are expecting something other than what I got, please let us know.
<img width="2261" alt="Screenshot 2023-10-09 at 12 23 43 AM" src="https://github.com/touchlab/Kermit/assets/68384/207e65fa-2db7-4091-82f3-6096f4a49659">

**Comment by kpgalligan** [comment]
Well, besides the duplicate log, but I don't think that's a Kermit thing as much as a Compose on iOS/App architecture thing.

**Comment by sunildhiman90** [comment]
Ok. -@kpgalligan thnx,I will check it again in my original project from xcode. But one question here. If i run ios app from android studio, then i dont get logs. So does kermit thing only logs for ios in xcode but not in android studio? Or is there any work around exist for showing ios logs in Android Studio as well?

**Comment by kpgalligan** [comment]
By default, Kermit has a method that picks the platform log writer that makes sense for development.

`platformLogWriter()`

https://github.com/touchlab/Kermit/blob/main/kermit-core/src/commonMain/kotlin/co/touchlab/kermit/platformLogWriter.kt#L17

Your code does call that here:

```kotlin
Logger.setLogWriters(platformLogWriter(NoTagFormatter))
```

`platformLogWriter` is an expect function that is only there for convenience. On Apple-based targets, it'll return an instance of `XcodeSeverityWriter`. That ultimately writes to `_os_log_internal`, which is an Apple-platform log. Presumably, the Android Studio KMM plugin does not monitor this, although I haven't tried.

The simplest answer is to use an instance of `CommonWriter`. That will print all logs, but you'll lose the formatting on Android and Xcode. Alternatively, you could add `CommonWriter` and the platform default, but that might result in duplicate log statements.

```kotlin
Logger.setLogWriters(platformLogWriter(NoTagFormatter), CommonWriter(NoTagFormatter))
```

Beyond that, create an `expect` helper function of your own, like `platformLogWriter`. Have it return `LogcatWriter` for Android and `CommonWriter` for iOS.

Also, possibly submit an issue to JetBrains to pull in the Apple-platform logs.

**Comment by sunildhiman90** [comment]
Thanku so much @kpgalligan for such detailed explanation. I got the whole idea now. I will check with the last option. Thanku.

**Comment by sunildhiman90** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/3796
