### ISSUE TITLE
Android Logcat logs are not being printed on 2.0.0-RC3

### ISSUE THREAD

**Issue by Nek-12** [touchlab/Kermit#341]
Kermit: 2.0.0-RC3

The issue is basically that: The logs are simply never printed.
Kermit is using the default configuration with platformLogWriter()
The Log.d() calls, for example, produce normal logs. 
Kermit is initialized in an Android module and used in multiple modules, including kotlin/kmm ones, throughout the app.

**Comment by kpgalligan** [comment]
We were calling `isLoggable` with the idea that that would be an efficient thing to do, but apparently `isLoggable` does something we didn't expect.

https://github.com/touchlab/Kermit/pull/342

Removed in PR and will be published soon.

Thanks for the issue!

**Comment by kpgalligan** [comment]
https://github.com/touchlab/Kermit/releases/tag/2.0.0-RC4

**Comment by Nek-12** [comment]
Seems like your pipeline failed due to api surface change 🙃

**Comment by Nek-12** [comment]
Hey, the pipeline is still dead. Any news?

**Comment by kpgalligan** [comment]
Ah, I had rushed out the update release. `2.0.0-RC4` should be fine. I sent a PR with the API dump and waiting on that to build. The only difference is that method removal, but that should have no impact on using `2.0.0-RC4`.

https://github.com/touchlab/Kermit/pull/343/files
