### ISSUE TITLE
Issue building iOS app when using 2.0.0-RC5

### ISSUE THREAD

**Issue by Yollty** [touchlab/Kermit#361]
Although the iOS app builds fine with RC4 when adding the RC5 library I am getting the following:

error: Could not find "/Users/me/.gradle/caches/modules-2/files-2.1/co.touchlab/kermit-iossimulatorarm64/2.0.0-RC5/3c5a418ae1db88130b59c1d75cdcd2a2832b357c/kermit.klib" in [/Users/me/Development/yollty-kmm-business-2/iosApp/Pods, /Users/me/.konan/klib, /Users/me/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.20/klib/common, /Users/me/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.20/klib/platform/ios_simulator_arm64]

Any idea what might cause that? For the moment I am downgrading back to RC4

**Comment by russhwolf** [comment]
It looks like you're building with Kotlin 1.8.20. Try bumping to 1.9.0.

**Comment by Yollty** [comment]
Indeed I am, can't bump to 1.9.0. for the moment due to other libraries not being compatible with 1.9.0 yet. But I did not see anywhere that 1.9.0 was required. Sorry if I missed it.

**Comment by phileo** [comment]
Is there a version of Kermit which supports Kotlin 1.8.20 ?

**Comment by Yollty** [comment]
2.0.0-RC4 was working for me with 1.8.20

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by findjigar** [comment]
Closing the issue as `2.0.0-RC4 was working for me with 1.8.20` according to https://github.com/touchlab/Kermit/issues/361#issuecomment-1693728643
