### ISSUE TITLE
Support for the new kotlin WASM target

### ISSUE THREAD

**Issue by Ic-ks** [touchlab/Kermit#362]
Hi,
Jetbrains started to provide library versions of [ktor](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/io/ktor/ktor-client-core/), [kotlinx.serialization](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/kotlinx-serialization-core/) and some other libraries for the already available wasm target:

```
kotlin {
// ...
    @Suppress("OPT_IN_USAGE")
    wasm {
        browser()
    }
}
```
It would be nice if kermit could support the wasm target, too.

BTW thanks for this library. Great work!

**Comment by kpgalligan** [comment]
Yeah, I think it's time. I don't know off hand, does console work the same in WASM?

**Comment by Ic-ks** [comment]
I also hoped that it comes with the same console, but it didn't. I think the background is that a wasm can be executed outside of a browser. I could workaround it by declaring the [console](https://github.com/touchlab/Kermit/compare/main...Ic-ks:Kermit-wasm:main#diff-a2c6241c15e56943e8a30cbd6bd4c807529bf2a84a22ae29c7087f9d82f35bf2) again. I forked the project, here are the [changes](https://github.com/touchlab/Kermit/compare/main...Ic-ks:Kermit-wasm:main) I did to support at least `wasm { browser() } `. If you want, I can create a pull request?


I think for wasms which are not executed in a browser, there are still some things to do. I discovered following maybe related code in the generated `example.uninstantiated.mjs` of my wasm example project:
```
            if (isBrowser) {
                console.error(text, ...styles);
            } else {
                const t = "\n" + text;
                if (typeof console !== "undefined" && console.log !== void 0)
                    console.log(t);
                else
                    print(t);
            }
```
Nevertheless wasm is still experimental so I think in the future they will provide a proper logging interface and logic to differ between a browser wasm and any other wasm is forgiven effort.

**Comment by HoffiMuc** [comment]
any idea on a new release date supporting wasm ?

**Comment by sunildhiman90** [comment]
@kpgalligan So does it support wasm now or its still in planning phase? Or If its in progress, any idea when release will be availabe with wasm support?

**Comment by HoffiMuc** [comment]
it does, yes.

**Comment by sunildhiman90** [comment]
thanx @HoffiMuc
