### ISSUE TITLE
Kermit changelog

### ISSUE THREAD

**Issue by dzmpr** [touchlab/Kermit#382]
Please publish changelog with each release. You not provided information about what changed in 2.x version comparing to 1.x. And further releases published without any information about changes.

**Comment by darronschall** [comment]
On a related note, is the chisel gradle plugin still being developed / supported? Or was that dropped with the v2 changes? It was removed from the README and the deleted from the website docs, but [plugin code still exits](https://github.com/touchlab/Kermit/blob/96281ab581c0ff0d85ebc375b3bace675c7c5696/plugin/kermit-ir-plugin/src/main/kotlin/co/touchlab/kermit/irplugin/KermitChiselTransformer.kt#L24).

**Comment by dzmpr** [comment]
@kpgalligan hi, can you please give some attention to this? There is no changelog in the next (2.0.3) release.

**Comment by dzmpr** [comment]
@findjigar Hi, can you please add changelog for the latest release? As I can see you actively contribute to this project.

For the future: it's very easy to automate, just add a changelog file that would be published as a description of a release.
