### ISSUE TITLE
Feature Request: Support for CLI applications

### ISSUE THREAD

**Issue by vegidio** [touchlab/Kermit#392]
Does Kermit support CLI applications?
I got it working in my iOS app, but when I tried to create a CLI application using KMP, it didn't print anything in my terminal. It only worked after I created a custom `LogWriter`, like this:

```kotlin
class YourCustomWriter : LogWriter() {
    override fun log(severity: Severity, message: String, tag: String, throwable: Throwable?) {
        println(message)
    }
}

Logger.setLogWriters(YourCustomWriter())
Logger.d { "Test" }
```

**Comment by kpgalligan** [comment]
Platform loggers don't necessarily write to system out. We have a few CLI tools that build natively for macos, and in those, to use Kermit to log to system out, we need to set the log writer.

[CommonWriter](https://github.com/touchlab/Kermit/blob/7250c8e5799eca9500afb6ce0aed8ff764c00236/kermit-core/src/commonMain/kotlin/co/touchlab/kermit/CommonWriter.kt#L19) exists to write out directly to system out.

Now, system error is unfortunately platform-specific, so supporting that would require a fairly custom and targeted writer implementation. That might be something to add, but we'd need to start with a definition of what platforms on which one would bulid a CLI tool. JVM, macos, linux, windows? Anybody writing CLI tools that get run in a JS context? WASM? Could do it, but `println` is a whole lot easier, so for now we just have that.
