### ISSUE TITLE
Logs are not chunked on Android

### ISSUE THREAD

**Issue by Nek-12** [touchlab/Kermit#394]
Kermit does not split long log statements into separate log invocations. As a result, any string longer than 4096 characters is cut off (not printed fully). This disallows using Kermit for e.g. http response logging. An example implementation of message splitting can be taken from Ktor or [FlowMVI](https://github.com/respawn-app/FlowMVI/blob/a819a78654509f155511681b98a7d2ea72ed904c/core/src/androidMain/kotlin/pro/respawn/flowmvi/logging/ChunkedLog.kt)

**Comment by samhill303** [comment]
We think the best way to accomplish this would be to implement a "ChunkedLogWriter" that can be used if desired as opposed to updating the default implementation. We a log writer that does that chunking could definitely be useful though. We'll add to our backlog, but welcome Pull Requests

**Comment by Nek-12** [comment]
The default implementation should be to send logs as chunked. Most people wouldn't expect their logs to just suddenly be cut off.

**Comment by Nek-12** [comment]
Yes, as far as I know, only android restricts log lines to 4096 symbols. Other platforms probably have 65536 char limits.

**Comment by samhill303** [comment]
2.0.4 has been deployed with @psh 's ChunkedLogWriter. Thanks for the input and let us know if you have any issues
