### ISSUE TITLE
Feature request: log to files

### ISSUE THREAD

**Issue by rocketraman** [touchlab/Kermit#405]
Sometimes it is useful to log on Android and iOS to files, which can easily be zipped up and transferred for remote analysis.

Now that [kotlinx-io](https://github.com/Kotlin/kotlinx-io) has been released and supports multiplatform filesystem writes (via okio, and works at least for most platforms including Android and iOS), it would be great if Kermit would leverage this to provide filesystem writing capability out of the box, rather than having users roll their own `LogWriter`s.

For a logging tool, it would be useful also to support automatic roll-overs and deletion of older logs.

**Comment by kpgalligan** [comment]
Any thoughts on good models for this with other logging libraries? For mobile, do other logging libraries have default folders to store to and any kind of built-in functionality for wrapping up files? Probably nothing with actually sending them, but I could see returning a file reference to the zip.

It would be easier to essentially replicate an existing library that people seem to use vs writing something entirely new.

**Comment by kpgalligan** [comment]
If you have a rough structure in mind, yeah, a PR would be good. I'd probably release this as another module rather than directly in `kermit-core`, at least to start. It can be focused more on mobile, or at least platforms that would support files easily (not JS).
