### ISSUE TITLE
Logs Not Appearing in Firebase Crashlytics with Kermit in Kotlin Multiplatform Using GitLive Firebase SDK

### ISSUE THREAD

**Issue by mhristev** [touchlab/Kermit#407]
I’m using the GitLive Firebase SDK in a Kotlin Multiplatform project and have integrated Kermit for logging. The logs, including exceptions, appear in `Logcat`, but they are not being sent to `Firebase Crashlytics`. I’m using `CrashlyticsLogWriter()` to route logs from Kermit to Crashlytics in Android-specific code.

build.gradle in `shared`:
```kotlin
sourceSets {
        commonMain.dependencies {
            api(libs.gitlive.firebase.kotlin.crashlytics)
            implementation("co.touchlab:kermit:2.0.4")
            implementation("co.touchlab:kermit-crashlytics:2.0.4")
            implementation("co.touchlab.crashkios:crashlytics:0.9.0")
        }
    }

```
`androidMain`:

```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        SharedLogger.initializeCrashlyticsLogging()
        SharedLogger.logInfo("In the onCreate()")

        setContent {
            App()
        }
    }
}
```

SharedLogger in `commonMain`
```kotlin

object SharedLogger {
    val logger: Logger = Logger.withTag("SharedLogger")

    @OptIn(ExperimentalKermitApi::class)
    fun initializeCrashlyticsLogging() {
        Logger.addLogWriter(CrashlyticsLogWriter())
        logInfo("In the init in shared")
    }


    fun logError(exception: Throwable, message: String) {
        logger.e(exception) { message }
    }

    fun triggerEveryTypeOfSeverityLog() {
        logger.v { "This is a verbose log message" }
        logger.d { "This is a debug log message" }
        logger.i { "This is an info log message" }
        logger.w { "This is a warning log message" }
        logger.e { "This is an error log message" }
        logger.a { "This is an assert log message" }
    }

    fun logInfo(message: String) {
        logger.i { message }
    }
}
```

I am trying to call `triggerCrashOutOfBounds()` which is in `shared/commonMain`, from the Android UI:

```kotlin
fun triggerCrashOutOfBounds() {
    val myList = listOf(1, 2, 3)
    SharedLogger.logInfo("Calling triggerCrashOutOfBounds().")
    try {
        val element = myList[5] 
    } catch (e: IndexOutOfBoundsException) {
        SharedLogger.logError(e, "Out of bounds error occurred.")

        throw e
    }
}
```

In the Crashlytics page in Firebase I can see only:

```log
1. Info: (SharedLogger) In the onCreate()

2. Info: (SharedLogger) In the init in shared
```

The logs from the `triggerCrashOutOfBounds` are completely lost. Any ideas? (iOS can send all the logs to Crashlytics, even those from `triggerCrashOutOfBounds` )

**Comment by samhill303** [comment]
There may be an issue with the way GitLive handles initializing Crashlytics and it's interaction with Kermit. Can you provide a minimal reproducing project for us to take a look at?

**Comment by mhristev** [comment]
Here is a link to the demo project: https://github.com/mhristev/KMP-Kermit-Crashlytics

**Comment by mhristev** [comment]
Here is a link to the demo app: https://github.com/mhristev/KMP-Kermit-Crashlytics

**Comment by kpgalligan** [comment]
I ran the app locally. I changed the app id and created a crashlytics app. Tried the crash button on Android and got the attached log.

That is what you're expecting to see, just to confirm? Are you missing statements always or is it intermittent?

![Screenshot 2024-11-19 at 1 50 11 PM](https://github.com/user-attachments/assets/323c57e3-1d78-44be-aac1-1083bbccb53f)

**Comment by mhristev** [comment]
Yes, this is what I expect to see. However, in the Crashlytics app, I consistently only get the first three logs from the bottom, with the top two always missing. I’ve tried over 100 times, but it’s always the same result.

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/e08fdb85-919a-4b62-a839-e2af0461492f">

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/862d0e56-ad9e-4d54-b4d8-be975645f678">

**Comment by mhristev** [comment]
We were able to reproduce the issue on a different machine. When running on Android 14, all five logs appear in the Crashlytics app. However, when switching to Android 15, only the three logs shown in the screenshot above are displayed. Did you test your crashes on Android 14 or Android 15?

**Comment by kpgalligan** [comment]
Closing for now. I'm adding it to our internal backlog for somebody to look into if there's time. However, Kermit is just a passthrough for log calls, as is CrashKiOS underneath it. There's nothing in either that would be different between different versions of Android, or at least, nothing that either is doing intentionally:

## Kermit

The log message winds up in the `log` function, which calls into `CrashlyticsCallsActual`.

```Kotlin
class CrashlyticsLogWriter(
    // Etc
) : LogWriter() {

    private val crashlyticsCalls: CrashlyticsCalls = CrashlyticsCallsActual()

    override fun log(severity: Severity, message: String, tag: String, throwable: Throwable?) {
        crashlyticsCalls.logMessage(
            messageStringFormatter.formatMessage(severity, Tag(tag), Message(message))
        )
        // Etc
    }
}
```

## CrashKiOS

`CrashlyticsCallsActual` directly calls into Crashlytics.

```Kotlin
actual class CrashlyticsCallsActual : CrashlyticsCalls {
    override fun logMessage(message: String) {
        FirebaseCrashlytics.getInstance().log(message)
    }
    //Etc
}
```

My guess is you're seeing some kind of timing issue in Crashlytics. However, Kermit doesn't do anything batched or async. When you finally throw the exception, those log calls would have completed.
