### ISSUE TITLE
Issue with Kotlin 2.1.0, kotlinx-serialization, and Kermit on WASM

### ISSUE THREAD

**Issue by ryanmitchener** [touchlab/Kermit#420]
I initially reported this issue here: https://youtrack.jetbrains.com/issue/KT-73549. After further triage I found there was an issue with using kotlinx-serialization and Kermit with Kotlin 2.1.0 and building to WASM. Removing the Kermit library dependency from the build allows the application to build. I'm not sure what is causing the issue, but here is a sample reproduction project.
[KotlinProject.zip](https://github.com/user-attachments/files/17984644/KotlinProject.zip)

**Comment by KevinSchildhorn** [comment]
Can you try updating to kermit to `2.0.5`? That seems to solve the issue on my end.

**Comment by ryanmitchener** [comment]
That did fix it. The update wasn't showing up in my libs.versions.toml for some reason.
