### ISSUE TITLE
Crash reporting logger

### ISSUE THREAD

**Issue by samhill303** [touchlab/Kermit#46]
How do we interact with crashkios and crash report tools like crashlytics. Might need modules with dependencies. might need to direct people to route interfaces to kermit

**Comment by samhill303** [comment]
It would be good generally to have some more complicated custom logger examples. Logging to other services in particular. Crash services like Crashlytics might be a good place to start

**Comment by mrf7** [comment]
Adding Trello ticket for content proposal
