### ISSUE TITLE
Add normal logging methods beside the closure ones

### ISSUE THREAD

**Issue by tonisives** [touchlab/Kermit#91]
If I cast an object from a generic property to a more specific one, then this smart cast is not available in the d{ } closure

<img width="747" alt="Screenshot 2021-07-26 at 09 59 13" src="https://user-images.githubusercontent.com/1083534/126927162-f794a131-75d6-410b-881a-4aa18165f306.png">

If I define a normal method:
```
fun Kermit.d(message:String) {
    this.d { message }
}
```
Then the smart cast is available

**Comment by kpgalligan** [comment]
Non-lambda functions added in 1.0 reworked version
